[package]
name = "santa-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
env_logger = "0.10.0"
csv = "1.2.2"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
ctrlc2 = "3.5.6"