[package]
name = "santa-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
env_logger = "0.10.0"
ctrlc2 = "3.5.6"
santa-solver-lib = { path = "./santa-solver-lib" }
csv = "1.3.0"
